#! /bin/sh

# Master script that validates and collates all the log files to prepare the final log file, which will be inserted into inserted into vendor_product_transactions_log table

transaction_log_folder="/var/www/CrawlFish/public/transactions_logs/$1"
search_log_folder="/var/www/CrawlFish/public/search_logs/$1"
merchant_log_folder="/var/www/CrawlFish/public/merchants_logs/$1"
script_path="/var/www/CrawlFish/script/transaction_logs_script"

if test -e $transaction_log_folder
then
cd $transaction_log_folder

if test -e $transaction_log_folder/final_logs
then
rm -r $transaction_log_folder/final_logs/*
else
mkdir final_logs
fi

for file in `ls *.dat`
do

file_name=`echo $file`

awk -F\| '{ if ($2 ~ /impressions/) print $1"|"$3; }' $file > $transaction_log_folder/final_logs/impressions1.dat
if test -e $transaction_log_folder/final_logs/impressions1.dat
then
awk -f $script_path/remove_duplicates.awk $transaction_log_folder/final_logs/impressions1.dat > $transaction_log_folder/final_logs/impressions2.dat
awk -F\| '{ if ($1 ~ /,/) {sub(/,/,"|",$1);} print $1"|"$2;}' $transaction_log_folder/final_logs/impressions2.dat > $transaction_log_folder/final_logs/impressions2-1.dat
awk -F\| '{ for(i=1;i<NF;i++) print "|"$i"|"$NF; }' $transaction_log_folder/final_logs/impressions2-1.dat > $transaction_log_folder/final_logs/impressions3.dat
awk -f $script_path/remove_duplicates.awk $transaction_log_folder/final_logs/impressions3.dat > $transaction_log_folder/final_logs/impressions4.dat
cat $transaction_log_folder/final_logs/impressions4.dat >> $transaction_log_folder/final_logs/final_impressions.dat
rm -r $transaction_log_folder/final_logs/impressions*
fi

awk -F\| '{ if ($2 ~ /clicks/) print $1"|"$3;  }' $file > $transaction_log_folder/final_logs/clicks1.dat
if test -e $transaction_log_folder/final_logs/clicks1.dat
then
awk -f $script_path/remove_duplicates.awk $transaction_log_folder/final_logs/clicks1.dat > $transaction_log_folder/final_logs/clicks2.dat
awk -F\| '{ if ($1 ~ /,/) {sub(/,/,"|",$1);} print $1"|"$2; }' $transaction_log_folder/final_logs/clicks2.dat > $transaction_log_folder/final_logs/clicks2-1.dat
awk -F\| '{ for(i=1;i<NF;i++) print "|"$i"|"$NF; }' $transaction_log_folder/final_logs/clicks2-1.dat > $transaction_log_folder/final_logs/clicks3.dat
awk -f $script_path/remove_duplicates.awk $transaction_log_folder/final_logs/clicks3.dat >> $transaction_log_folder/final_logs/clicks4.dat
cat $transaction_log_folder/final_logs/clicks4.dat >> $transaction_log_folder/final_logs/final_clicks.dat
rm -r $transaction_log_folder/final_logs/clicks*
fi

awk -F\| '{ if(NR > 1) { print $1"|'$file_name'" } }' $file >> $transaction_log_folder/final_logs/unique_keys.dat
awk -f $script_path/remove_duplicates.awk $transaction_log_folder/final_logs/unique_keys.dat > $transaction_log_folder/final_logs/final_unique_keys.dat

rm -r $transaction_log_folder/final_logs/unique_keys.dat

awk -F\| '{ if(NR > 1) {if(length($0) == 0) next; print $3} }' $file >> $transaction_log_folder/final_logs/keywords.dat

log_date=`awk -F\  '{ if (NR == 1) print $1 }' $file`

done

awk -f $script_path/remove_duplicates.awk $transaction_log_folder/final_logs/keywords.dat >> $transaction_log_folder/final_logs/final_keywords.dat
rm -r $transaction_log_folder/final_logs/keywords.dat

cd $transaction_log_folder/final_logs

if test -e final_clicks.dat -a -s final_clicks.dat
then
	mysql -u root -p'Sector@123' -e "LOAD DATA LOCAL INFILE '$transaction_log_folder/final_logs/final_clicks.dat' INTO TABLE temp_transactions_logs FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n' SET type='clicks',log_date='$log_date',created_at=CURRENT_TIMESTAMP" crawlfishdevdb
echo "clicks logged successfully into table"
else
echo "no clicks present"
fi

if test -e final_impressions.dat -a -s final_impressions.dat
then
	mysql -u root -p'Sector@123' -e "LOAD DATA LOCAL INFILE '$transaction_log_folder/final_logs/final_impressions.dat' INTO TABLE temp_transactions_logs FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n' SET type='impressions',log_date='$log_date',created_at=CURRENT_TIMESTAMP" crawlfishdevdb
echo "impressions logged successfully into table"
else
echo "no impressions present"
fi

cd
else
echo "no transactions present today"
fi

if test -e $search_log_folder
then 
cd $search_log_folder

if test -e $search_log_folder/final_logs
then
rm -r $search_log_folder/final_logs/*
else
mkdir final_logs
fi

for file in `ls *.dat`
do

awk -F\| '{ if (NR > 1) print "|"$1"|"$2 }' $file >> $search_log_folder/final_logs/searchkeys.dat

log_date=`awk -F\  '{ if (NR == 1) print $1 }' $file`

done

awk -f $script_path/remove_duplicates.awk $search_log_folder/final_logs/searchkeys.dat > $search_log_folder/final_logs/final_searchkeys.dat
rm -r $search_log_folder/final_logs/searchkeys.dat

cd $search_log_folder/final_logs

if test -e final_searchkeys.dat -a -s final_searchkeys.dat
then
	mysql -u root -p'Sector@123' -e "LOAD DATA LOCAL INFILE '$search_log_folder/final_logs/final_searchkeys.dat' INTO TABLE temp_searchkey_logs FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n' SET log_date='$log_date',created_at=CURRENT_TIMESTAMP" crawlfishdevdb
echo "search keys successfully logged into table"
else
echo "no search keys present"
exit 1
fi

cd
else
echo "no search logs present today"
fi

if test -e $merchant_log_folder
then
cd $merchant_log_folder

if test -e $merchant_log_folder/final_logs
then
rm -r $merchant_log_folder/final_logs/*
else
mkdir final_logs
fi

for file in `ls *.dat`
do

count=`awk '{print NR}' $file | tail -1`
if test $count -eq 2
then 
awk -F\| '{ if (NR == 1) printf "|"$2"|"$3"|"$4"|"$1; if (NR == 2) printf "|"$1"\n"; }' $file >> $merchant_log_folder/final_logs/final_merchant_logs.dat
elif test $count -eq 1
then
awk -F\| '{ if ($5 == "login") print "|"$2"|"$3"|"$4"|"$1"|"; else if ($5 == "logout") print "|"$2"|"$3"|"$4"|""|"$1; }' $file >> $merchant_log_folder/final_logs/final_merchant_logs.dat
fi

done

log_date=$1;

cd $merchant_log_folder/final_logs

if test -e final_merchant_logs.dat -a -s final_merchant_logs.dat
then
	mysql -u root -p'Sector@123' -e "LOAD DATA LOCAL INFILE '$merchant_log_folder/final_logs/final_merchant_logs.dat' INTO TABLE temp_merchant_logs FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n' SET log_date='$log_date',created_at=CURRENT_TIMESTAMP" crawlfishdevdb
echo "merchant actions successfully logged into table"
else
echo "merchant logs absent"
exit 1
fi

cd
else
echo "no merchant transactions present today"
fi
